### ISSUE TITLE
Fail Getting Started in Windows 7 x64

### ISSUE THREAD

**Issue by jmptrader** [sigmaframeworks/sigma-ui-framework#16]
Hi,

I'm following your instructions ,
1.  After of **npm install sigma-ui-framework --save**

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current:
os":"win32","arch":"x64"})
1. Replace generated & update manually <project_dir>/aurelia_project/aurelia.json
2. After **au run --watch**
       [SyntaxError: Unexpected token /]

-- x --
Any help is welcome, Thank's,

JM

**Comment by adarshpastakia** [comment]
Have not tried working it on windows, but the first issue would seem to be due to sass/compass.
The second issue im not sure if its to do with the paths in aurelia.json

**Comment by jmptrader** [comment]
Hi Adarsh,

Then development environment suggested is linuxOS or macOS.

Thanks,
JM
