### ISSUE TITLE
Pagination on ui-datagrid

### ISSUE THREAD

**Issue by emcga** [sigmaframeworks/sigma-ui-framework#7]
@adarshpastakia I was wondering the proper way to set up pagination on the ui-datagrid element. I didn't see anything in the docs that explains how to do it. Also, there were a few ways I could see implementing it, but I wanted to follow the framework.

**Comment by emcga** [comment]
Ah, just found the pager. But on line 15 of ui-pager.html I changed to the following below.

``` html
<span> of 5</span>
```

to

``` html
<span> of ${total}</span>
```

I guess I'll use a 2D array to store the table items. I will first divide the array from the server into smaller chunks that will fit in my 2D array. So the total pages will be the length of the "first-dimension" of the array, and the current property from the pager will be used to fetch the contents of each "first-dimension". This will then be used to populate another array that will be bound to the data-list property of the ui-datagrid. Does that sound reasonable?

Thanks for your time.

**Comment by adarshpastakia** [comment]
@emcga yes that would work

``` html
<ui-pager total.bind='data.length' current.bind='__page'></ui-pager>
<ui-datagrid data-list.bind='data[__page]'></ui-datagrid>
```

right now I'm working on enhancing the data grid to use `aurelia-ui-virtualization` for large data rendering. i tested it yesterday it works well, need to fix a few layout issues on it once done i will push a new update
